export {
    buildOrderCopyEmailContent,
    buildOrderCustomerEmailContent,
    buildOrderDeveloperEmailContent,
    buildOrderEmail,
    buildOrderEmailFromManageDetail,
    mapManageOrderDetailToOrderEmailData,
    type BuildOrderEmailOptions,
    type MapOrderEmailDataOptions,
    type OrderEmailAddress,
    type OrderEmailContent,
    type OrderEmailCustomer,
    type OrderEmailData,
    type OrderEmailFulfillment,
    type OrderEmailLineItem,
    type OrderEmailPayment,
    type OrderEmailTotals,
} from '@/lib/email/order-email-template';
